version: '3.8'
services:
  frontend:
    image: hendrik127/err_frontend:latest
    environment:
      NODE_ENV: production
    command: sh -c "nginx -g 'daemon off;'"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - scraper-api
    restart: on-failure:5
  scraper-api:
    image: hendrik127/err_api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "python3 database.py && uvicorn main:app --host 0.0.0.0 --port 3000"

    ports:
      - "3000:3000"
    environment:
      ENVIRONMENT: production
      DATABASE_URL: "postgresql://postgres:password@database:5432/scraperdb"  # Update with your PostgreSQL database URL
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:password@database:5432/scraperdb"  # Add SQLAlchemy database URI
    depends_on:
      - database  # Make sure scraper-api service waits for the database service to be up
    restart: on-failure:5

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scraperdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
