version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    depends_on:
      - scraper-api
    restart: on-failure:5
  scraper-api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: sh -c "python3 database.py && uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - "./api:/api"
    ports:
      - "80:80"
    environment:
      DATABASE_URL: "postgresql://postgres:password@database:5432/scraperdb"  # Update with your PostgreSQL database URL
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:password@database:5432/scraperdb"  # Add SQLAlchemy database URI

    depends_on:
      - database
    restart: on-failure:5

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scraperdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
