name: CD Pipeline

on: 
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull repository
        run: git clone https://github.com/hendrik127/err_scarper.git
      - name: cd into repository
        run: cd err_scraper
      - name: Run Docker
        run: docker compose -f docker-compose.prod.yml up -d


