name: CD Pipeline

on: 
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull repository
        run: git clone git@github.com:hendrik127/err_text_to_speech.git
      - name: cd into repository
        run: cd err_text_to_speech
      - name: Run Docker
        run: docker compose -f docker-compose.prod.yaml up -d


