name: CD Pipeline

on: 
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        run: git clone git@github.com:hendrik127/err_text_to_speech.git 
      - name: cd into repository
        run: cd err_text_to_speech
      - name: Pull repository
        run: git pull
      - name: Stop current
        run: sudo docker stop $(sudo docker ps -aq) 
      - name: Remove containers
        run: sudo docker rm $(sudo docker ps -aq) 
      - name: Remove images
        run: sudo docker rmi $(sudo docker images -q)
      - name: Run Docker
        run: docker compose -f docker-compose.prod.yaml up -d


