name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Build the Docker images.
      run: |
        docker-compose up -d --build
        docker-compose ps
    - name: Push to Dockerhub.
      run: docker push hendrik127/err_scraper-frontend:latest
        docker push hendrik127/err_scraper-api:latest
